# Generated by Django 2.0.13 on 2019-05-16 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='photo',
            field=models.ImageField(null=True, upload_to='static/'),
        ),
    ]
